# ============================================================
#  MEST-C Component Classification Config
# ============================================================

common:
  seed: 1208
  cuda_device: "0"

data:
  partition_csv: "/mnt/disk3/liuyang/LYcom/awholeprocess/前瞻性数据集/iga微调2/partition.csv"
  image_feat_dir: "/mnt/disk3/liuyang/TransMIL-main/process/conch_G1_1120"

mestc:
  save_dir: "/mnt/disk3/liuyang/LYcom/awholeprocess/前瞻性数据集/iga微调2/mestc"
  batch_size: 1
  lr: 1.0e-4
  epochs: 100
  num_workers: 0
